server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wandie123/springclud-demo.git
          searchPaths: config
          username: 2934566741@qq.com
          password: wandie19961101
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
